name: Flow2
on: [push, workflow_dispatch] # workflow_dispatch is there because we want to manually trigger this event
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Final Print
        run: echo "Successfully done Everything."
  deploy:
    needs: [test] # is used when you want to run the deploy job after test job (if test fails it will never start)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Final Print
        run: echo "Successfully done in flow2 Everything."
      - name: Build Project
        run: echo "npm run build"
      - name: Run the Deploy to Host it anywhere
        run: echo "Deploying"
