name: RealWorkFlow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Code
      - uses: actions/setup-node@v3
      - name: Install nodejs
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Final Print
        run: echo "Successfully done Everything."
